=== Ogolar/Earthdawn-Character-Editor/config/earthdawntranslation.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/translation" xmlns="http://earthdawn.com/translation" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="translationlabel_type">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="lang" type="edt:language_type" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="TRANSLATION_type">
		<xs:choice maxOccurs="unbounded">
			<xs:element maxOccurs="unbounded" minOccurs="0" name="LABEL" type="translationlabel_type"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="TRANSLATIONS">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element maxOccurs="unbounded" minOccurs="0" name="CAPABILITY" type="TRANSLATION_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="SPELL" type="TRANSLATION_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="DISCIPLINE" type="TRANSLATION_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="ITEM" type="TRANSLATION_type"/>
			</xs:sequence>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Ogolar/Earthdawn-Character-Editor/config/translation/CathayPlayersGuideED3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TRANSLATIONS rulesetversion="ED3" xmlns="http://earthdawn.com/translation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://earthdawn.com/translation ../earthdawntranslation.xsd">
	<CAPABILITY>
		<LABEL lang="en">Absorb Spell</LABEL>
		<LABEL lang="de">Zauber Auffangen</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Ambush</LABEL>
		<LABEL lang="de">Hinterhalt</LABEL>				
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Beast Summons</LABEL>
		<LABEL lang="de">Bestie Herbeirufen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Bedazzle</LABEL>
		<LABEL lang="de">Verblenden</LABEL>
	</CAPABILITY>	
	<CAPABILITY>
		<LABEL lang="en">Blade Blur</LABEL>
		<LABEL lang="de">Klingen Flirren</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Blade Dance</LABEL>
		<LABEL lang="de">Schwerttanz</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Block and Counter</LABEL>
		<LABEL lang="de">Block und Konter</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Block Spell</LABEL>
		<LABEL lang="de">Zauber Abblocken</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Calm Beast</LABEL>
		<LABEL lang="de">Bestie Beruhigen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Close In</LABEL>
		<LABEL lang="de">Reingehen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Combo</LABEL>
		<LABEL lang="de">Combo</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Commune</LABEL>
		<LABEL lang="de">Zwiesprache</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Company of One</LABEL>
		<LABEL lang="de">Begleitung des Einen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Conceal Caravan</LABEL>
		<LABEL lang="de">Gefährt Verbergen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Counteract</LABEL>
		<LABEL lang="de">Entgegenwirken</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Create Moon Staff</LABEL>
		<LABEL lang="de">Mondstab Erschaffen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Cross</LABEL>
		<LABEL lang="de">Durchziehen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Cyclone</LABEL>
		<LABEL lang="de">Windhose</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Disguise Chest</LABEL>
		<LABEL lang="de">Truhe Maskieren</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Doom Circle</LABEL>
		<LABEL lang="de">Kreis der Verdammnis</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Dragonfire</LABEL>
		<LABEL lang="de">Drachenfeuer</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Dragonscales</LABEL>
		<LABEL lang="de">Drachenschuppen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Duel</LABEL>
		<LABEL lang="de">Duell</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Embrace of the Phoenix</LABEL>
		<LABEL lang="de">Umarmung des Phoenix</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Feather Light</LABEL>
		<LABEL lang="de">Federleicht</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Feign Retreat</LABEL>
		<LABEL lang="de">Fingierter Rückzug</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Fiery Blade</LABEL>
		<LABEL lang="de">Flammende Klinge</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Flowing Blow</LABEL>
		<LABEL lang="de">Fließender Schlag</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Gift of the Phoenix</LABEL>
		<LABEL lang="de">Geschenk des Phönix</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Great Kick</LABEL>
		<LABEL lang="de">Gewaltiger Tritt</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Great Strike</LABEL>
		<LABEL lang="de">Gewaltiger Schlag</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Guard Stance</LABEL>
		<LABEL lang="de">Verteidigungshaltung</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Hook</LABEL>
		<LABEL lang="de">Festhacken</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Improvised Poultice</LABEL>
		<LABEL lang="de">Improvisierter Salbenverband</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Inherited Powers</LABEL>
		<LABEL lang="de">Ererbte Fähigkeit</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Inner Strength</LABEL>
		<LABEL lang="de">Innere Stärke</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Jab</LABEL>
		<LABEL lang="de">Schneller Schlag</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Joint Lock</LABEL>
		<LABEL lang="de">Gelenkhebel</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Kiai</LABEL>
		<LABEL lang="de">Kiai</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Kip</LABEL>
		<LABEL lang="de">Kip</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Knockout</LABEL>
		<LABEL lang="de">Knockout</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Legendary Blades</LABEL>
		<LABEL lang="de">Legendäre Klingen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Lightning Born</LABEL>
		<LABEL lang="de">Blitzgeboren</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Lightning Combo</LABEL>
		<LABEL lang="de">Blitzschnelle Kombination</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Liquid Prison</LABEL>
		<LABEL lang="de">Flüssiges Gefängnis</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Manifest Beast</LABEL>
		<LABEL lang="de">Tier Manifestieren</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Meditate</LABEL>
		<LABEL lang="de">Meditieren</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Mind Hand</LABEL>
		<LABEL lang="de">Gedankengriff</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Moon Ray</LABEL>
		<LABEL lang="de">Mondstrahl</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Moon Shield</LABEL>
		<LABEL lang="de">Mondschild</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Past Tongues</LABEL>
		<LABEL lang="de">Ehemalige Sprachen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Path of the Righteous</LABEL>
		<LABEL lang="de">Pfad des Gerechten</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Phantom Strike</LABEL>
		<LABEL lang="de">Phantomangriff</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Purge Pattern</LABEL>
		<LABEL lang="de">Struktur Säubern</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Rapid Strike</LABEL>
		<LABEL lang="de">Rascher Schlag</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Regeneration</LABEL>
		<LABEL lang="de">Regeneration</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Rundown</LABEL>
		<LABEL lang="de">Umfahren</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Sense Animals</LABEL>
		<LABEL lang="de">Tiere Erspüren</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Shadow Step</LABEL>
		<LABEL lang="de">Schattenschritt</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Shield of the Innocent</LABEL>
		<LABEL lang="de">Schild der Unschuldigen</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Spirit Blend</LABEL>
		<LABEL lang="de">Seelengemisch</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Steer Wagon</LABEL>
		<LABEL lang="de">Wagen Lenken</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Store Knowledge</LABEL>
		<LABEL lang="de">Wissen Speichern</LABEL>				
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Takedown</LABEL>
		<LABEL lang="de">Zu Boden Bringen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Task Kin</LABEL>
		<LABEL lang="de">Verwandte Seele Beauftragen</LABEL>				
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Thunderer's Astrology</LABEL>
		<LABEL lang="de">***</LABEL>				
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Touch of the Phoenix</LABEL>
		<LABEL lang="de">Berührung des Phoenix</LABEL>				
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Trading</LABEL>
		<LABEL lang="de">Handeln</LABEL>				
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Uppercut</LABEL>
		<LABEL lang="de">Uppercut</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Wind Slash</LABEL>
		<LABEL lang="de">Windhieb</LABEL>		
	</CAPABILITY>	
</TRANSLATIONS>

=== Ogolar/Earthdawn-Character-Editor/config/translation/NamegiversED3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TRANSLATIONS rulesetversion="ED3" xmlns="http://earthdawn.com/translation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://earthdawn.com/translation ../earthdawntranslation.xsd">
	<CAPABILITY>
		<LABEL lang="en">Armored Fetish</LABEL>
		<LABEL lang="de">Gepanzerter Fetisch</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Bear Mark</LABEL>
		<LABEL lang="de">Mal Tragen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Bird Song</LABEL>
		<LABEL lang="de">Vogelgesang</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Body Control</LABEL>
		<LABEL lang="de">Körperkontrolle</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Buzz</LABEL>
		<LABEL lang="de">Schwirren</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Cast Net</LABEL>
		<LABEL lang="de">Netz Werfen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Clay Skin</LABEL>
		<LABEL lang="de">Tonhaut</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Create Fetish</LABEL>
		<LABEL lang="de">Fetisch Erschaffen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Dive Attack</LABEL>
		<LABEL lang="de">Sturzflug</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Earth Bond</LABEL>
		<LABEL lang="de">Erdverbindung</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Enhanced Fetish</LABEL>
		<LABEL lang="de">Erweiterter Fetisch</LABEL>
	</CAPABILITY>	
	<CAPABILITY>
		<LABEL lang="en">Engaging Dance</LABEL>
		<LABEL lang="de">Klingentanz</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">False Shackles</LABEL>
		<LABEL lang="de">Falsche Fesseln</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Fast Grab</LABEL>
		<LABEL lang="de">Schnelles Zupacken</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Free Mind</LABEL>
		<LABEL lang="de">Freier Geist</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Freedom Search</LABEL>
		<LABEL lang="de">Freiheitssuche</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Gliding</LABEL>
		<LABEL lang="de">Gleiten</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Heal Slave</LABEL>
		<LABEL lang="de">Sklaven Heilen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Heart of Freedom</LABEL>
		<LABEL lang="de">Herz der Freiheit</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Hoard Blows</LABEL>
		<LABEL lang="de">Schläge Horten</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Missile Path</LABEL>
		<LABEL lang="de">Schussfeld</LABEL>
	</CAPABILITY>	
	<CAPABILITY>
		<LABEL lang="en">Pilot Boat</LABEL>
		<LABEL lang="de">Boot Steuern</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Prison Call</LABEL>
		<LABEL lang="de">Gefängnisruf</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Read River</LABEL>
		<LABEL lang="de">Fluss Lesen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Shared Fetish</LABEL>
		<LABEL lang="de">Summenfetisch</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Shout of Jusice</LABEL>
		<LABEL lang="de">Ruf der Gerechtigkeit</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Spell Fetish</LABEL>
		<LABEL lang="de">Zauberfetisch</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Suppress Influence</LABEL>
		<LABEL lang="de">Einfluss Unterdrücken</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Swimming</LABEL>
		<LABEL lang="de">Schwimmen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Tail Dance</LABEL>
		<LABEL lang="de">Schwanztanz</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Wind Dance</LABEL>
		<LABEL lang="de">Windtanz</LABEL>
	</CAPABILITY>	
	<CAPABILITY>
		<LABEL lang="en">Woodspeak</LABEL>
		<LABEL lang="de">Waldsprache</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Woodwalk</LABEL>
		<LABEL lang="de">Waldwandeln</LABEL>		
	</CAPABILITY>	
</TRANSLATIONS>

=== Ogolar/Earthdawn-Character-Editor/config/translation/PlayersCompendiumED3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TRANSLATIONS rulesetversion="ED3" xmlns="http://earthdawn.com/translation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://earthdawn.com/translation ../earthdawntranslation.xsd">

	<CAPABILITY>
		<LABEL lang="en">Animal Leadership</LABEL>
		<LABEL lang="de">Tiere Führen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Animated Dead</LABEL>
		<LABEL lang="de">Leiche Beleben</LABEL>
	</CAPABILITY>	
	<CAPABILITY>
		<LABEL lang="en">Animate Object</LABEL>
		<LABEL lang="de">Gegenstand Beleben</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Armored Matrix</LABEL>
		<LABEL lang="de">Gepanzerter Matrix</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Astral Pocket</LABEL>
		<LABEL lang="de">Astraltasche</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Astral Web</LABEL>
		<LABEL lang="de">Astralnetz</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Aura Armor</LABEL>
		<LABEL lang="de">Aurarüstung</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Bardic Voice</LABEL>
		<LABEL lang="de">Bardenstimme</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Bestial Resilience</LABEL>
		<LABEL lang="de">Tierische Härte</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Bestial Toughness</LABEL>
		<LABEL lang="de">Tierische Zähigkeit</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Blood Guilt Weapon</LABEL>
		<LABEL lang="de">Waffe der Blutschuld</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Body Blade</LABEL>
		<LABEL lang="de">Körperklinge</LABEL>		
	</CAPABILITY>	
	<CAPABILITY>
		<LABEL lang="en">Bone Compass</LABEL>
		<LABEL lang="de">Knochenkompass</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Call Mount</LABEL>
		<LABEL lang="de">Reittier Rufen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Casting Pattern</LABEL>
		<LABEL lang="de">Zauberstruktur</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Chameleon</LABEL>
		<LABEL lang="de">Chamäleon</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Champion Challenge</LABEL>
		<LABEL lang="de">Herausforderung der Besten</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Confront Horror</LABEL>
		<LABEL lang="de">Dämonen Entgegentreten</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Critical Hit</LABEL>
		<LABEL lang="de">Kritischer Treffer</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Defense</LABEL>
		<LABEL lang="de">Verteidigung</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Detect Falsehood</LABEL>
		<LABEL lang="de">Falschheit Erkennen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Detect Influence</LABEL>
		<LABEL lang="de">Einfluss Entdecken</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Develop Animal Sense</LABEL>
		<LABEL lang="de">Tiersinne Entwickeln</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Dominate Arrow</LABEL>
		<LABEL lang="de">Pfeil Beherrschen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Eagle Eye</LABEL>
		<LABEL lang="de">Adlerauge</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Earth Armor</LABEL>
		<LABEL lang="de">Irdene Rüstung</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Echo Location</LABEL>
		<LABEL lang="de">Echolot</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Effect Pattern</LABEL>
		<LABEL lang="de">Struktur Beeinflussen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Elemental Walk</LABEL>
		<LABEL lang="de">Elementarwandeln</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Endure Cold</LABEL>
		<LABEL lang="de">Kälte Ertragen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Enduring Art</LABEL>
		<LABEL lang="de">Dauerhafte Kunst</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Escape Divination</LABEL>
		<LABEL lang="de">Fluchtweg Ahnen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Ethereal Weapon</LABEL>
		<LABEL lang="de">Ätherwaffe</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">First Ring of Perfection</LABEL>
		<LABEL lang="de">Ansatz zur Perfektion</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Gold Sense</LABEL>
		<LABEL lang="de">Goldgespür</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Howl</LABEL>
		<LABEL lang="de">Heulen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Impossible Hide</LABEL>
		<LABEL lang="de">Unmögliches Versteck</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Impressive Strike</LABEL>
		<LABEL lang="de">Beeindruckender Schlag</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Incite Mob</LABEL>
		<LABEL lang="de">Mob Aufwiegeln</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Incite Stampede</LABEL>
		<LABEL lang="de">Stampede</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Infuse Armor</LABEL>
		<LABEL lang="de">Rüstung Verstärken</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Infuse Blade</LABEL>
		<LABEL lang="de">Klinge Verstärken</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Infuse Weapon</LABEL>
		<LABEL lang="de">Waffe Verstärken</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Lion Spirit</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Matrix Strike</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Memorize Image</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Metal Ward</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Mind Armor</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Mind Blade</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Missile Twister</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Moving Earth</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Multi-Charge</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Multi-Shot</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Multi-Strike</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Multi-Tongue</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Multi-Weaving</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Netherwalk</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Pin</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Plant Shelter</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Questor</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Quick Shot</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Rally</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Range Pattern</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Reshape Object</LABEL>
		<LABEL lang="de">***</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Resist Pain</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Rushing Attack</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Safe Thought</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Scent Identifier</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Screaming Arrow</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Second Chance</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Sense Magic Item</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Shackle Shrug</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Shared Matrix</LABEL>
	</CAPABILITY>	
	<CAPABILITY>
		<LABEL lang="en">Shield Beater</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Soften Blade</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Song of Deflection</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Soul Shatter</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Spell Crystal Lock</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Spirit Strike</LABEL>
	</CAPABILITY>	
	<CAPABILITY>
		<LABEL lang="en">Stone Skin</LABEL>
	</CAPABILITY>	
	<CAPABILITY>
		<LABEL lang="en">Storm Shield</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Summoning Circle</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Thoughtful Expression</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Thunder Axe</LABEL>
	</CAPABILITY>	
	<CAPABILITY>
		<LABEL lang="en">Trace Missile</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Trample</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Truth Skit</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Unmount</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Venom</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Vital Strike</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Vitality</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Warning Shot</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Warp Missile</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Water Dancing</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Weapon Breaker</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Weapon Ward</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Whirlwind</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Wind Bow</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Wound Transfer</LABEL>
	</CAPABILITY>	
</TRANSLATIONS>

=== Ogolar/Earthdawn-Character-Editor/config/translation/GamemastersGuideED3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TRANSLATIONS rulesetversion="ED3" xmlns="http://earthdawn.com/translation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://earthdawn.com/translation ../earthdawntranslation.xsd">

	<CAPABILITY>
		<LABEL lang="en">Astral Camouflage</LABEL>
		<LABEL lang="de">Astrale Tarnung</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Aura Of Awe</LABEL>
		<LABEL lang="de">Aura der Ehrfurcht</LABEL>		
	</CAPABILITY>	
	<CAPABILITY>
		<LABEL lang="en">Bargain With Summoned Creature</LABEL>
		<LABEL lang="de">Feilschen mit beschworenem Wesen</LABEL>		
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Corrupt Karma</LABEL>
		<LABEL lang="de">Karma Verderben</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Corrupt Reality</LABEL>
		<LABEL lang="de">Realität Verderben</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Create Shadow</LABEL>
		<LABEL lang="de">Schatten Erschaffen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Cursed Luck</LABEL>
		<LABEL lang="de">Verfluchtes Glück</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Damage Shift</LABEL>
		<LABEL lang="de">Schadenstransfer</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Disease</LABEL>
		<LABEL lang="de">Krankheit</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Displace</LABEL>
		<LABEL lang="de">Versetzen</LABEL>
	</CAPABILITY>	
	<CAPABILITY>
		<LABEL lang="en">Gain Surprise</LABEL>
		<LABEL lang="de">Überrumpelung</LABEL>
	</CAPABILITY>	
	<CAPABILITY>
		<LABEL lang="en">Intimidation</LABEL>
		<LABEL lang="de">Einschüchterung</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Karma Cancel</LABEL>
		<LABEL lang="de">Karmablockade</LABEL>
	</CAPABILITY>	
	<CAPABILITY>
		<LABEL lang="en">Mind Wave</LABEL>
		<LABEL lang="de">Gedankenwelle</LABEL>
	</CAPABILITY>	
</TRANSLATIONS>
