=== Ogolar/Earthdawn-Character-Editor/config/earthdawnoptionalrules.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/optionalrules" xmlns="http://earthdawn.com/optionalrules" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="OPTIONALRULE_type">
		<xs:attribute name="used" type="edt:yesno_type" default="no"/>
	</xs:complexType>
	<xs:complexType name="OPTIONALRULES_ATTRIBUTE">
		<xs:attribute name="points" type="xs:int" />
		<xs:attribute name="limitoneway" type="edt:yesno_type"/>
		<xs:attribute name="limitlpincrease" type="edt:unsigned_int" default="3"/>
	</xs:complexType>
	<xs:complexType name="OPTIONALRULES_ATTRIBUTEBASEDMOVEMENT">
		<xs:attribute name="attribute" type="edt:MOVEMENTATTRIBUTE_name_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="OPTIONALRULES_DEFAULTOPTIONALTALENT">
		<xs:attribute name="talent" type="xs:string" use="required"/>
		<xs:attribute name="circle" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="lang" type="edt:language_type" use="required"/>
		<xs:attribute name="discipline" type="edt:unsigned_int" default="1"/>
	</xs:complexType>
	<xs:complexType name="OPTIONALRULES_MULTIUSETALENT">
		<xs:attribute name="talent" type="xs:string" use="required"/>
		<xs:attribute name="count" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="lang" type="edt:language_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="OPTIONALRULES_DEFAULTLANGUAGE">
		<xs:complexContent>
			<xs:extension base="edt:CHARACTERLANGUAGE_type">
				<xs:attribute name="lang" type="edt:language_type" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="OPTIONALRULES_ORIGIN">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="DEFAULTLANGUAGE" type="OPTIONALRULES_DEFAULTLANGUAGE"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="NAME_STARTINGWEAPONS_type">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="unbounded" name="WEAPON" type="edt:WEAPON_type"/>
		</xs:sequence>
		<xs:attribute name="lang" type="edt:language_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="NAME_STARTINGITEMS_type">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="unbounded" name="ITEM" type="edt:ITEM_type"/>
		</xs:sequence>
		<xs:attribute name="lang" type="edt:language_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="NAME_STARTINGSKILLS_type">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="unbounded" name="SKILL" type="edt:SKILL_type"/>
		</xs:sequence>
		<xs:attribute name="lang" type="edt:language_type" use="required"/>
	</xs:complexType>
	<xs:element name="OPTIONALRULES">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="1" name="ATTRIBUTE" type="OPTIONALRULES_ATTRIBUTE"/>
				<xs:element minOccurs="1" maxOccurs="1" name="STARTRANKS" type="edt:USEDSTARTRANKS_type"/>
				<xs:element minOccurs="1" maxOccurs="1" name="ATTRIBUTEBASEDMOVEMENT" type="OPTIONALRULES_ATTRIBUTEBASEDMOVEMENT"/>
				<xs:element minOccurs="1" maxOccurs="1" name="LEGENDPOINTSFORATTRIBUTEINCREASE" type="OPTIONALRULE_type"/>
				<xs:element minOccurs="1" maxOccurs="1" name="SPELLLEGENDPOINTCOST" type="OPTIONALRULE_type"/>
				<xs:element minOccurs="1" maxOccurs="1" name="KARMALEGENDPOINTCOST" type="OPTIONALRULE_type"/>
				<xs:element minOccurs="1" maxOccurs="1" name="THREADITEMDOSTACK" type="OPTIONALRULE_type"/>
				<xs:element minOccurs="1" maxOccurs="1" name="AUTOINCREMENTDISCIPLINETALENTS" type="OPTIONALRULE_type"/>
				<xs:element minOccurs="1" maxOccurs="1" name="SHOWDEFAULTSKILLS" type="OPTIONALRULE_type"/>
				<xs:element minOccurs="1" maxOccurs="1" name="QUESTORTALENTNEEDLEGENDPOINTS" type="OPTIONALRULE_type"/>
				<xs:element minOccurs="1" maxOccurs="1" name="AUTOINSERTLEGENDPOINTSPENT" type="OPTIONALRULE_type"/>
				<xs:element minOccurs="1" maxOccurs="1" name="KEEPLEGENDPOINTSYNC" type="OPTIONALRULE_type"/>
				<xs:element minOccurs="1" maxOccurs="1" name="LANGUAGESASINDIVIDUALSKILLS" type="OPTIONALRULE_type"/>
				<xs:element minOccurs="1" maxOccurs="1" name="ENDURINGARMORBYSTRENGTH" type="OPTIONALRULE_type"/>
				<xs:element minOccurs="1" maxOccurs="1" name="ALIGNINGTALENTSANDSKILLS" type="OPTIONALRULE_type"/>
				<xs:element minOccurs="1" maxOccurs="1" name="DATEFORMAT" type="xs:string"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="MULTIUSETALENT" type="OPTIONALRULES_MULTIUSETALENT"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="DEFAULTOPTIONALTALENT" type="OPTIONALRULES_DEFAULTOPTIONALTALENT"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="ORIGIN" type="OPTIONALRULES_ORIGIN"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="STARTINGWEAPONS" type="NAME_STARTINGWEAPONS_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="STARTINGITEMS" type="NAME_STARTINGITEMS_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="STARTINGSKILLS" type="NAME_STARTINGSKILLS_type"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Ogolar/Earthdawn-Character-Editor/config/optionalrules.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<OPTIONALRULES xmlns="http://earthdawn.com/optionalrules" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/optionalrules earthdawnoptionalrules.xsd">
	<!--
	By the following rule you can define how many attribute buy points can be used during character creation.
	If you set limitoneway to "no", not only the left attribute buy points will increase the maximum karma,
	but also to many spent points will decrease the maximum karma.
	-->
	<ATTRIBUTE points="25" limitoneway="yes" limitlpincrease="3"/>
	<!--
	By the following rule you can define how many start ranks a character will receive during the character creation
	Usually:
	 - 8 ranks for talents
	 - 2 ranks for knowledge skill
	 - 2 ranks for speaking skills
	 - 1 rank for read/write language skill
	 - 1 rank for artisan skill
	 - 8 ranks for other skills
	-->
	<STARTRANKS talents="8" skills="14"/>
	<!--
	By the following rule you can define which attribute will modify the racial movement rate
	right now implemented are racial movement rate modifier based on "STR", "DEX" or "na"
	The last on means no movement rate modification.
	-->
	<ATTRIBUTEBASEDMOVEMENT attribute="STR+DEX"/>
	<!-- By the following rule you can define if the attribute increase will cost legend points or not -->
	<LEGENDPOINTSFORATTRIBUTEINCREASE used="yes"/>
	<!--
	By the following rule you can define if the freely learned spell will cost legend points or not
	The spells ability set by the discipline circle will never cost legend points
	-->
	<SPELLLEGENDPOINTCOST used="yes"/>
	<!--
	By the following rule you can define if the karma points will cost legend points or not
	-->
	<KARMALEGENDPOINTCOST used="yes"/>
	<!--
	By the following rule you can define if all modifier of thread items will be added or
	if only the maximum of each modifier will count.
	-->
	<THREADITEMDOSTACK used="yes"/>
	<!--
	By the following rule you can define if the all discipline talent will be automatically increase
	to met the circle increase requirement, but be care full this can result in to many spent legend points
	-->
	<AUTOINCREMENTDISCIPLINETALENTS used="yes"/>
	<!-- By the following rule you can define if the default skills will be displayed where possible -->
	<SHOWDEFAULTSKILLS used="yes"/>
	<!-- By the following rule you can define if a questor need to spend legend points for his questor talent -->
	<QUESTORTALENTNEEDLEGENDPOINTS used="yes"/>
	<!--
	By the following rule you can define if the editor will auto insert legend points into the experience table
	But note, that this rule will only insert not delete entries from the experience table.
	E.g., if you increase and reduce steps form talents you will get multiple entries and you have to decide
	which is the right one and which can be deleted. You still in response for your legend point entries.
	 -->
	<AUTOINSERTLEGENDPOINTSPENT used="no"/>
	<KEEPLEGENDPOINTSYNC used="yes"/>
	<!--
	By the following rule you can define if the editor will request a skill for each learned languages.
	-->
	<LANGUAGESASINDIVIDUALSKILLS used="no"/>
	<!--
	By the following rule you can define if the strong characters are more capable at wearing heavy armor than weaker characters.
	-->
	<ENDURINGARMORBYSTRENGTH used="no"/>
	<!--
	By the following rule you can define if skill will be aligned to talents.
	In case of 'yes', learning a talent which is already learned as skill will not necessarily start with rank 1.
	Players Guide page 240
	-->
	<ALIGNINGTALENTSANDSKILLS used="no"/>
	<!--
	If a date should be printed this defines the format of the date and time
	http://download.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html
	-->
	<DATEFORMAT>yyyy-MM-dd HH:mm</DATEFORMAT>
	<!-- The following Rule can be added multiple times and will define which talents can be used more than ones and how many at maximum -->
	<!-- <MULTIUSETALENT talent="xxx" lang="en" count="10"/> -->
	<!-- By the following rule you can define if if a specific talent will be added automatically and will not cost an optional talent slot -->
	<!-- <DEFAULTOPTIONALTALENT talent="Durability" circle="2" lang="en"/>  uncomment this item to get the durability as an extra talent-->
	<ORIGIN name="Barsaive">
		<DEFAULTLANGUAGE lang="en" language="Dwarf" speak="skill" readwrite="skill"/>
	</ORIGIN>
	<ORIGIN name="Cathay">
	</ORIGIN>
	<ORIGIN name="Thera">
		<DEFAULTLANGUAGE lang="en" language="Theran" speak="skill" readwrite="skill"/>
	</ORIGIN>
	<ORIGIN name="Vasgothia">
		<DEFAULTLANGUAGE lang="en" language="Vasgothia" speak="skill" readwrite="skill"/>
	</ORIGIN>
	<ORIGIN name="Creana">
		<DEFAULTLANGUAGE lang="en" language="Creana" speak="skill" readwrite="skill"/>
	</ORIGIN>
	<ORIGIN name="Marac">
		<DEFAULTLANGUAGE lang="en" language="Maracan" speak="skill" readwrite="skill"/>
	</ORIGIN>
	<ORIGIN name="Indrisa">
		<DEFAULTLANGUAGE lang="en" language="Indrisan" speak="skill" readwrite="skill"/>
	</ORIGIN>
	<STARTINGWEAPONS lang="de">
		<WEAPON name="Messer" damagestep="2" strengthmin="4" weight="1" size="1" shortrange="5" longrange="10" kind="melee weapon"/>
	</STARTINGWEAPONS>
	<STARTINGWEAPONS lang="en">
		<WEAPON name="Dagger" damagestep="2" strengthmin="4" weight="1" size="1" shortrange="5" longrange="10" kind="melee weapon"/>
	</STARTINGWEAPONS>
	<STARTINGITEMS lang="de">
		<ITEM name="Rucksack, Schlafsack, &amp;steel, Wasserschlauch, groÃŸer Sack" weight="13"/>
		<ITEM name="Fackel" weight="1" kind="light"/>
		<ITEM name="Kunsthandwerk Werkzeug (to be specified)" weight="5" kind="tool"/>
		<ITEM name="Grimoir (nur bei Zauberer)" weight="3" kind="book"/>
		<ITEM name="Reisekleidung (soft boots, shirt, belt, robe or breeches, traveler's cloak)" weight="3" kind="cloth"/>
		<ITEM name="Reiseproviant (1 Woche)" weight="1" kind="food"/>
	</STARTINGITEMS>
	<STARTINGITEMS lang="en">
		<ITEM name="backpack, bedroll, flint&amp;steel, waterskin, large sack" weight="13"/>
		<ITEM name="torch" weight="1" kind="light"/>
		<ITEM name="artisan tool (to be specified)" weight="5" kind="tool"/>
		<ITEM name="grimoire (magicans only)" weight="3" kind="book"/>
		<ITEM name="Traveler's Garb (soft boots, shirt, belt, robe or breeches, traveler's cloak)" weight="3" kind="cloth"/>
		<ITEM name="Trail Rations (1 week)" weight="1" kind="food"/>
	</STARTINGITEMS>
	<STARTINGSKILLS lang="en">
		<SKILL name="Speak Language">
			<edt:RANK rank="2" startrank="2"/>
		</SKILL>
		<SKILL name="Read/Write Language">
			<edt:RANK rank="1" startrank="1"/>
		</SKILL>
		<SKILL name="Knowledge">
			<edt:LIMITATION>TBD</edt:LIMITATION>
			<edt:RANK rank="1" startrank="1"/>
		</SKILL>
		<SKILL name="Knowledge">
			<edt:LIMITATION>TBD</edt:LIMITATION>
			<edt:RANK rank="1" startrank="1"/>
		</SKILL>
		<SKILL name="Artisan">
			<edt:LIMITATION>TBD</edt:LIMITATION>
			<edt:RANK rank="1" startrank="1"/>
		</SKILL>
	</STARTINGSKILLS>
</OPTIONALRULES>
